=== BeratUlualan/DirectoryTrends/config/config.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "cluster": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "port": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "access_token": {
          "type": "string"
        }
      },
      "required": [
        "address",
        "port",
        "username",
        "password",
        "access_token"
      ]
    },
    "influxdb": {
      "type": "object",
      "properties": {
        "address": {
          "type": "string"
        },
        "token": {
          "type": "string"
        },
        "bucket_name": {
          "type": "string"
        },
        "org_name": {
          "type": "string"
        }
      },
      "required": [
        "address",
        "token",
        "bucket_name",
        "org_name"
      ]
    },
    "email": {
      "type": "object",
      "properties": {
        "from": {
          "type": "string"
        },
        "to": {
          "type": "string"
        },
        "login": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "server": {
          "type": "string"
        },
        "port": {
          "type": "integer"
        },
        "use": {
          "type": "string"
        }
      },
      "required": [
        "from",
        "to",
        "login",
        "password",
        "server",
        "port",
        "use"
      ]
    },
    "directories": {
      "type": "object",
      "properties": {
        "dir_paths": {
          "type": "array",
          "items": [
            {
              "type": "string"
            }
          ]
        },
        "max_depth": {
          "type": "integer"
        }
      },
      "required": [
        "dir_paths",
        "max_depth"
      ]
    }
  },
  "required": [
    "cluster",
    "influxdb",
    "email",
    "directories"
  ]
}

=== BeratUlualan/DirectoryTrends/config/config.json
{
	"cluster" : {
		"address" : "CLUSTER_ADDRESS",
        "port" : "8000",
		"username" : "", 
		"password" : "",
        "access_token": ""
	},
    "influxdb" : {
        "address" : "INFLUXDB ADRESS",
        "token" : "INFLUXDB_TOKEN",
	"bucket_name" : "BUCKET_NAME",
	"org_name" : "ORG_NAME"
    },
    "email":{
        "from": "from@mail.com",
        "to": "to@mail.com",
        "login": "",
        "password": "",
        "server": "SMTP SERVER ADDRESS",
        "port": 25,
        "use": "none"
    },
    "directories": {
        "dir_paths": ["/Dir1","/Dir2"],
        "max_depth": 0
    }
}
